# Generated by Django 4.0.3 on 2022-03-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoBackend', '0002_alter_todolist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deadline_date',
            field=models.DateField(null=True),
        ),
    ]
